name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Create ZAP working directories
        run: |
          sudo mkdir -p /zap/wrk
          sudo chmod -R 777 /zap
          mkdir -p reports

      # Опционально: создаём конфигурационный файл ZAP
      - name: Create ZAP configuration
        run: |
          cat > zap-config.yaml << EOF
          env:
            contexts:
              - name: "Default Context"
                urls: ["http://localhost:8080"]
            parameters:
              failOnError: false
              progressToStdout: true
          EOF
          sudo mv zap-config.yaml /zap/wrk/zap.yaml
          sudo chmod 644 /zap/wrk/zap.yaml

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I'
          allow_issue_writing: false
          artifact_name: 'zap-scan-results'
          format: 'html'
          working_directory: /zap/wrk
          docker_options: '-v /zap/wrk:/zap/wrk:rw'

      - name: Move ZAP Report
        run: |
          sudo find /zap/wrk -name "*.html" -exec cp {} reports/zap-report.html \;
          sudo chmod 644 reports/zap-report.html || true
          
      - name: Upload ZAP Results
        uses: actions/upload-artifact@v3
        with:
          name: zap-results
          path: reports/zap-report.html
          retention-days: 14
